Update to deb8.5-lua5.3-Bdb5.3

diff --git a/bin/first b/bin/first
--- a/bin/first
+++ b/bin/first
@@ -46,7 +46,7 @@ logmsg  " The following packages or programs are required. Be prepared to enter 
 logmsg 
 cd
 if yorn "Would you like to install the required packages now??"; then
-  for i in autoconf automake autotools-dev g++ gcc gccxml gdb git libc6-dev libdb-dev libtool make screen libreadline-gplv2-dev libncurses5-dev libneon27 libaprutil1-dev openjdk-7-jre openjdk-7-jre-headless libgtest-dev libssl-dev liblua5.1-0-dev
+  for i in libdb5.3-dev wget autoconf automake autotools-dev g++ gcc gccxml gdb git libc6-dev libdb-dev libtool make screen libreadline-gplv2-dev libncurses5-dev libneon27 libaprutil1-dev openjdk-7-jre openjdk-7-jre-headless libgtest-dev libssl-dev
       do
         logmsg " Installing ${i} ... "
         sudo apt-get -q -y install ${i} &>> ~/Documents/pkglog.txt
@@ -58,27 +58,26 @@ fi
 
 #################
 # Lua install
-# INFO -wget http://www.lua.org/ftp/lua-5.1.4.tar.gz ## saved to home/setup/
+# INFO -wget http://www.lua.org/ftp/lua-5.3.3.tar.gz ## saved to home/setup/
 #################
 logstep "Lua 5.1.4 Install"
 
 dir=~/setup/
-lua_base=~/setup/lua-5.1.4.tar.gz
+lua_base=~/setup/lua-5.3.3.tar.gz
 lua_ins=/usr/local/bin/lua
 
 if [ -f $lua_ins ]; then
  logmsg "Great, looks like you have Lua installed.!"
   else
-    while ! yorn "Would you like to install Lua 5.1.4 now??"
+    while ! yorn "Would you like to install Lua 5.3.3 now??"
       do
         echo "***You need to do it before you can build the server.*** )"
         sleep 1
       done
   if [ ! -f $lua_base ]; then
-    logmsg "Downloading required lua package to /home/setup/. Please wait.."
+    logmsg "Downloading required lua package to ~/home/setup/. Please wait.."
     cd $dir
-    wget http://www.lua.org/ftp/lua-5.1.4.tar.gz
-    wget http://files.luaforge.net/releases/lnum/lnum/lnum-2009/lua514-lnum-20090417.patch.tgz
+    wget http://www.lua.org/ftp/lua-5.3.3.tar.gz
   fi
   logmsg
   logmsg "Restoring basic lua install from $lua_base"
@@ -86,67 +85,15 @@ if [ -f $lua_ins ]; then
   for dir in ~/setup/
     do
       cd $dir
-      tar xzf ~/setup/lua-5.1.4.tar.gz &>> ~/Documents/pkglog.txt
-      tar xzf ~/setup/lua514-lnum-20090417.patch.tgz
-      cd lua-5.1.4
-#FIXME      patch < ../lnum-2009/lua514-lnum-20090417.patch &>> ~/Documents/pkglog.txt
+      tar xzf ~/setup/lua-5.3.3.tar.gz &>> ~/Documents/pkglog.txt
+      cd lua-5.3.3
       sudo make linux install &>> ~/Documents/pkglog.txt
-      sudo make test
+      sudo make test &>> ~/Documents/pkglog.txt
       cd
     done
   logmsg " "
-  logmsg "You have successfully installed Lua if you see 'Hello world, from Lua 5.1!' in the terminal."
+  logmsg "You have successfully installed Lua if you see 'Hello world, from Lua 5.3!' in the terminal."
   logmsg " "
-fi
-
-####################
-# Berkely DB Install
-# wget http://download.oracle.com/berkeley-db/db-5.0.32.NC.tar.gz ## saved to home/setup/
-####################
-# TODO -Remove un-needed files
-# rm -R db-5.0.32.NC  NEEDED OR NOT?
-####################
-logstep "Berkely DB Install"
-
-dir=~/setup/
-bdb_base=~/setup/db-5.0.32.NC.tar.gz
-bdb_pkg=/usr/local/BerkeleyDB.5.0/include/db.h
-
-if [ -f $bdb_pkg ]; then
-  logmsg "Ok looks like you have installed Berkely DB-5.0!"
- else
-  while ! yorn " Would you like to install or restore Berkely DB from http://download.oracle.com/berkeley-db/db-5.0.32.NC.tar.gz now?? "
-    do
-      echo "You need to do it before you can build the server. (cntl+c to exit)"
-      sleep 1
-    done
-  if [ ! -f $bdb_base ]; then
-    logmsg "Missing $bdb_base did you remove it?"
-    logmsg "Downloading required Bdb package to /home/setup/. Please wait.."
-    cd setup
-    wget http://download.oracle.com/berkeley-db/db-5.0.32.NC.tar.gz
-  fi
-
-    logmsg
-    logmsg "Restoring Berkely DB install from $bdb_base"
-    logmsg
-     for dir in ~/setup/
-     do
-       cd $dir
-       tar xzf ~/setup/db-5.0.32.NC.tar.gz
-       cd db-5.0.32.NC
-       cd build_unix
-       sudo ../dist/configure --enable-cxx &>> ~/Documents/pkglog.txt
-       sudo make &>> ~/Documents/pkglog.txt
-       sudo make install &>> ~/Documents/pkglog.txt
-       cd ..
-       cd ..
-       echo "/usr/local/BerkeleyDB.5.0/lib" | sudo tee -a /etc/ld.so.conf
-       sudo ldconfig
-     done
-  logmsg
-  logmsg "Berkely DB installed. "
-  logmsg
 fi
 
 ##############################################################################
@@ -183,10 +130,9 @@ logstep "Finalizing install and removing un-needed files."
 #sudo apt-get autoremove | tee -a install.txt
 sudo service mysql start
 cd $dir
-rm db-5.0.32.NC.tar.gz
-rm lua-5.1.4.tar.gz
-#rm -R lua-5.1.4 
-#rm -R db-5.0.32.NC
+rm lua-5.3.3.tar.gz
+rm -R lua-5.3.3
+cd
 logmsg 
 logmsg "Run the 'first' script at any time to check installation of required programs."
 logmsg
